#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('topological-axis.png')"

#test -e topological-axis.png && rm topological-axis.png
jupyter labextension install @jupyterlab/latex@0.6.1
#nbconvert topological-axis.ipyynb --to pdf
#wget https://imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-7.0.10-23.x86_64.rpm
#wget https://imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-libs-7.0.10-23.x86_64.rpm
##rpm -Uvh ImageMagick-7.0.10-23.x86_64.rpm
##rpm -Uvh ImageMagick-libs-7.0.10-23.x86_64.rpm
#wget https://imagemagick.org/download/binaries/magick
#chmod 777 magick
# ./magick
# wget https://www.imagemagick.org/download/ImageMagick.tar.gz
# tar xf ImageMagick.tar.gz
# cd ImageMagick-7*
# ./configure
# make
# sudo make install
# sudo ldconfig /usr/local/lib
